Repository openMetadataInitiative/openMINDS_instances, pull requests merged in 2025-04, with the labels that each got.

#198 UBERON terms with 'organ' in their name
  instances/latest/terminologies/UBERONParcellation/chemosensoryOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/circumventricularOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/gustatoryOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/infundibularOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/otolithOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/parapinealOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/paraventricularOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/parietalOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/secretoryCircumventricularOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/sensoryCircumventricularOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/septalOrganOfMasera.jsonld
  instances/latest/terminologies/UBERONParcellation/subcommissuralOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/subfornicalOrgan.jsonld
  instances/latest/terminologies/UBERONParcellation/vestibularOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/chemosensoryOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/circumventricularOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/gustatoryOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/infundibularOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/otolithOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/parapinealOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/paraventricularOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/parietalOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/secretoryCircumventricularOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/sensoryCircumventricularOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/septalOrganOfMasera.jsonld
  instances/v3.0/terminologies/UBERONParcellation/subcommissuralOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/subfornicalOrgan.jsonld
  instances/v3.0/terminologies/UBERONParcellation/vestibularOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/chemosensoryOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/circumventricularOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/gustatoryOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/infundibularOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/otolithOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/parapinealOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/paraventricularOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/parietalOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/secretoryCircumventricularOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/sensoryCircumventricularOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/septalOrganOfMasera.jsonld
  instances/v4.0/terminologies/UBERONParcellation/subcommissuralOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/subfornicalOrgan.jsonld
  instances/v4.0/terminologies/UBERONParcellation/vestibularOrgan.jsonld
Labels: request

#262 Autopopulation pipeline
  .github/scripts/sync_instances.py
  .github/workflows/autopopulation.yml
Labels: technical

#64 EspINA ContentTypes
  instances/latest/contentTypes/application_vnd.espina.measurement+ms-excel.jsonld
  instances/latest/contentTypes/application_vnd.espina.segmentation.seg.jsonld
Labels: ContentType

#285 Fix #284
  .github/scripts/sync_instances.py
  instances/v3.0/contentTypes/application_vnd.espina.measurement+ms-excel.jsonld
  instances/v3.0/contentTypes/application_vnd.espina.segmentation.seg.jsonld
  instances/v4.0/contentTypes/application_vnd.espina.measurement+ms-excel.jsonld
  instances/v4.0/contentTypes/application_vnd.espina.segmentation.seg.jsonld
Labels: bug

#263 Reusable validation workflow from openMINDS_actions.
  .github/workflows/instance_validator.yml
Labels: technical
