Repository openMetadataInitiative/openMINDS_instances, pull requests merged in 2025-02, with the labels that each got.

#53 Create ContentTypes for WebAlign and Webwarp
  instances/latest/contentTypes/application_vnd.webalign.waln.jsonld
  instances/latest/contentTypes/application_vnd.webwarp.wwrp.jsonld
  instances/v3.0/contentTypes/application_vnd.webalign.waln.jsonld
  instances/v3.0/contentTypes/application_vnd.webwarp.wwrp.jsonld
  instances/v4.0/contentTypes/application_vnd.webalign.waln.jsonld
  instances/v4.0/contentTypes/application_vnd.webwarp.wwrp.jsonld
Labels: ContentType

#251 fixing type in StimulationTechnique
  instances/latest/terminologies/stimulationTechnique/subliminalVisualStimulation.jsonld
  instances/v3.0/terminologies/stimulationTechnique/subliminalVisualStimulation.jsonld
  instances/v4.0/terminologies/stimulationTechnique/subliminalVisualStimulation.jsonld
Labels: bug

#254 Fix @type typos
  instances/v3.0/contentTypes/application_vnd.webalign.waln.jsonld
  instances/v3.0/contentTypes/application_vnd.webwarp.wwrp.jsonld
Labels: bug

#255 Extra '/' in @type
  instances/v3.0/contentTypes/application_vnd.webalign.waln.jsonld
  instances/v3.0/contentTypes/application_vnd.webwarp.wwrp.jsonld
Labels: bug

#252 Adding missing PE to JBA (temporal lobe)
  instances/latest/parcellationEntities/JBA/JBA_temporalLobe.jsonld
  instances/v3.0/parcellationEntities/JBA/JBA_temporalLobe.jsonld
  instances/v4.0/parcellationEntities/JBA/JBA_temporalLobe.jsonld
Labels: bug, SANDS

#259 Corrected at_ids of all MRIWeighting terms (bug fix)
  instances/latest/terminologies/MRIWeighting/PDWeighting.jsonld
  instances/latest/terminologies/MRIWeighting/R2-starWeighting.jsonld
  instances/latest/terminologies/MRIWeighting/R2Weighting.jsonld
  instances/latest/terminologies/MRIWeighting/T1RhoWeighting.jsonld
  instances/latest/terminologies/MRIWeighting/T1Weighting.jsonld
  instances/latest/terminologies/MRIWeighting/T2-starWeighting.jsonld
  instances/latest/terminologies/MRIWeighting/T2Weighting.jsonld
Labels: bug, request
