Repository openMetadataInitiative/openMINDS_instances, pull requests merged in 2025-01, with the labels that each got.

#185 WHSSD atlas - typo fix
  instances/latest/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v1.01.jsonld
  instances/latest/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v2.jsonld
  instances/latest/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.01.jsonld
  instances/latest/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.jsonld
  instances/latest/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v4.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v1.01.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v2.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.01.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v4.jsonld
  instances/v4.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v1.01.jsonld
  instances/v4.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v2.jsonld
  instances/v4.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.01.jsonld
  instances/v4.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.jsonld
  instances/v4.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v4.jsonld
Labels: bug, SANDS

#186 MNI-Colin27 typo in 'hasVersions'
  instances/latest/commonCoordinateSpaces/MNI-Colin27.jsonld
  instances/v3.0/commonCoordinateSpaces/MNI-Colin27.jsonld
  instances/v4.0/commonCoordinateSpaces/MNI-Colin27.jsonld
Labels: bug, SANDS

#237 Name for JBA_frintalCingulateGryus does not match the file name
  instances/latest/parcellationEntities/JBA/JBA_frontalCingulateGyrus.jsonld
  instances/v3.0/parcellationEntities/JBA/JBA_frontalCingulateGyrus.jsonld
  instances/v4.0/parcellationEntities/JBA/JBA_frontalCingulateGyrus.jsonld
Labels: bug

#171 Simple JSON-LD files validator.
  .github/workflows/json-ld-validator.yml
Labels: request, technical

#244 Update GABA-A_BZ.jsonld
  instances/latest/terminologies/molecularEntity/GABA-A_BZ.jsonld
  instances/v3.0/terminologies/molecularEntity/GABA-A_BZ.jsonld
  instances/v4.0/terminologies/molecularEntity/GABA-A_BZ.jsonld
Labels: bug

#240 Rename generalLinearModelAnalysis.jsonld to generalLinearModeling.jsonld
  instances/latest/terminologies/analysisTechnique/generalLinearModeling.jsonld
  instances/v3.0/terminologies/analysisTechnique/generalLinearModeling.jsonld
  instances/v4.0/terminologies/analysisTechnique/generalLinearModeling.jsonld
Labels: bug

#241 Rename geneticRiskScoreAnalysis.jsonld to geneticRiskScore.jsonld
  instances/latest/terminologies/analysisTechnique/geneticRiskScore.jsonld
  instances/v3.0/terminologies/analysisTechnique/geneticRiskScore.jsonld
  instances/v4.0/terminologies/analysisTechnique/geneticRiskScore.jsonld
Labels: bug

#243 Rename 6,7-Dinitro-1,4-dihydroquinoxaline-2,3-dione.jsonld to 6,7-din…
  instances/latest/terminologies/molecularEntity/6,7-dinitro-1,4-dihydroquinoxaline-2,3-dione.jsonld
  instances/v3.0/terminologies/molecularEntity/6,7-dinitro-1,4-dihydroquinoxaline-2,3-dione.jsonld
  instances/v4.0/terminologies/molecularEntity/6,7-dinitro-1,4-dihydroquinoxaline-2,3-dione.jsonld
Labels: bug

#239 Rename deepLearningBasedAnalysis.jsonld to deepLearning.jsonld
  instances/latest/terminologies/analysisTechnique/deepLearning.jsonld
  instances/v3.0/terminologies/analysisTechnique/deepLearning.jsonld
  instances/v4.0/terminologies/analysisTechnique/deepLearning.jsonld
Labels: bug

#245 fixing atid in progammingLanguage AMPL
  instances/latest/terminologies/programmingLanguage/AMPL.jsonld
  instances/v4.0/terminologies/programmingLanguage/AMPL.jsonld
Labels: bug

#246 Rename infraredLight.jsonld to infraredNeuralStimulus.jsonld
  instances/latest/terminologies/opticalStimulusType/infraredNeuralStimulus.jsonld
  instances/v3.0/terminologies/opticalStimulusType/infraredNeuralStimulus.jsonld
  instances/v4.0/terminologies/opticalStimulusType/infraredNeuralStimulus.jsonld
Labels: bug

#249 fixing @id
  instances/v3.0/terminologies/programmingLanguage/AMPL.jsonld
Labels: bug
