Repository openMetadataInitiative/openMINDS_instances, pull requests merged in 2025-07, with the labels that each got.

#324 Add workflow for dynamically generating coverage statistics on instances.
  .github/workflows/statistics.yml
  README.md
  scripts/coverage/coverage.py
Labels: technical

#323 Fix #311 Update name in application_vnd.meshview+json.jsonld
  instances/latest/contentTypes/application_vnd.meshview+json.jsonld
Labels: bug

#328 Create cervusElaphus.jsonld
  instances/latest/terminologies/species/cervusElaphus.jsonld
Labels: request
