Repository openMetadataInitiative/openMINDS_instances, pull requests merged in 2025-08, with the labels that each got.

#335 Fix #334: replace @id licenses
  instances/v3.0/brainAtlasVersions/AAL1/AAL1_SPM12-v4.jsonld
  instances/v3.0/brainAtlasVersions/DWMA/DWMA_2018.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v1.13-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v1.18-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v1.18-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.2-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.2-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.4-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.4-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.5-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.5-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.6-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.9-BigBrain.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.9-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.9-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v2.9-fsaverage.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0-BigBrain.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0-fsaverage.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.1-BigBrain.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.1-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.1-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.1-fsaverage.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.2-BigBrain.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.2-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.2-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.2-fsaverage.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.3-BigBrain.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.3-Colin27.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.3-MNI152.jsonld
  instances/v3.0/brainAtlasVersions/JBA/JBA_v3.0.3-fsaverage.jsonld
  instances/v3.0/brainAtlasVersions/SWMA/SWMA_2018.jsonld
  instances/v3.0/brainAtlasVersions/Schaefer-400p/Schaefer-400p_2018-FSL-MNI152-kong17n.jsonld
  instances/v3.0/brainAtlasVersions/Schaefer-400p/Schaefer-400p_2018-FSL-MNI152-yeo17n.jsonld
  instances/v3.0/brainAtlasVersions/Schaefer-400p/Schaefer-400p_2018-FSL-MNI152-yeo7n.jsonld
  instances/v3.0/brainAtlasVersions/Schaefer-400p/Schaefer-400p_2018-fsLR32k-kong17n.jsonld
  instances/v3.0/brainAtlasVersions/Schaefer-400p/Schaefer-400p_2018-fsLR32k-yeo17n.jsonld
  instances/v3.0/brainAtlasVersions/Schaefer-400p/Schaefer-400p_2018-fsLR32k-yeo7n.jsonld
  instances/v3.0/brainAtlasVersions/SwansonBM/SwansonBM_3rd-ed.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v1.01.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v2.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.01.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v3.jsonld
  instances/v3.0/brainAtlasVersions/WHSSDatlas/WHSSDatlas_v4.jsonld
  instances/v3.0/commonCoordinateSpaceVersions/SwansonSRB/SwansonSRB_v1992.jsonld
Labels: bug

#339 New exp. approach and alignment of all their definitions
  instances/latest/terminologies/experimentalApproach/biophysics.jsonld
  instances/latest/terminologies/experimentalApproach/genetics.jsonld
  instances/latest/terminologies/experimentalApproach/pathology.jsonld
  instances/latest/terminologies/experimentalApproach/pharmacology.jsonld
Labels: request

#340 Fix openMINDS_actions/issues/20 - autopopulation folders generation
  .github/workflows/autopopulation.yml
Labels: bug

#75 Add LocareJSON ContentType
  instances/latest/contentTypes/application_vnd.locare+json.jsonld
Labels: ContentType

#343 add Standard YouTube License to license library
  instances/latest/licenses/youtube.jsonld
Labels: request

#66 Probeinterface ContentType
  instances/latest/contentTypes/application_vnd.spikeinterface.probeinterface+json.jsonld
Labels: ContentType
